[package]
name = "ia_challenge"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.98"
dotenvy = "0.15.7"
envy = "0.4.2"
priority-queue = "2.3.1"
rand = { version = "0.9.0", features = ["thread_rng"] }
serde = { version = "1.0.219", features = ["derive"] }
